"""
This file contains the API key for the API.
"""

MY_MARKET_NEWS_API_KEY = "MY_API_KEY"
REPORT_API_BASE_URL = "https://marsapi.ams.usda.gov/services/v1.2/reports/"
MARKET_API_BASE_URL = "https://mymarketnews.ams.usda.gov/get_external_api/result"

COMMODITY_CLASSES = ["ALL", "FRUITS", "ONIONS AND POTATOES", "VEGETABLES", "HERBS", "ORNAMENTALS", "HEMP"]
FRUIT_COMMODITIES = ["ALL", "APPLE PEARS", "APPLES", "APPLES, PROCESSED", "APRICOTS", "AVOCADOS", "BANANAS",
                     "BLACKBERRIES", "BLUEBERRIES", "CACTUS PEARS", "CANTALOUPS", "CHERRIES", "CLEMENTINES",
                     "CRANBERRIES", "GRAPEFRUIT", "GRAPES", "HONEYDEWS", "KIWIFRUIT", "LEMONS", "LIMES", "MANGOES",
                     "NECTARINES", "ORANGES", "PAPAYA", "PEACHES", "PEARS", "PERSIMMONS", "PINEAPPLES", "PLUMS",
                     "POMEGRANATES", "PRUNES", "RASPBERRIES", "SATSUMA", "STRAWBERRIES", "TANGELOS", "TANGERINES",
                     "WATERMELONS"]
ONIONS_AND_POTATOES_COMMODITIES = ["ALL", "ONIONS DRY", "POTATOES"]
VEGETABLES_COMMODITIES = ["ALL", "ARTICHOKES", "ASPARAGUS", "BEANS", "BEETS", "BOK CHOY", "BROCCOLI",
                          "BRUSSELS SPROUTS", "CABBAGE", "CACTUS LEAF (NOPALES)", "CARROTS", "CAULIFLOWER", "CELERY",
                          "CHAYOTE", "CHINESE CABBAGE", "COLLARD GREENS", "CORN-SWEET", "CUCUMBERS", "EGGPLANT",
                          "GARLIC", "KALE GREENS", "LETTUCE, BOSTON", "LETTUCE, GREEN LEAF", "LETTUCE, ICEBERG",
                          "LETTUCE, RED LEAF", "LETTUCE, ROMAINE", "MUSHROOMS", "MUSTARD", "ONIONS GREEN",
                          "PEPPERS, BELL TYPE", "PEPPERS, OTHER", "PUMPKINS", "RADISHES", "SALAD", "SPINACH", "SQUASH",
                          "SWEET POTATOES", "SWISS CHARD", "TOMATILLOS", "TOMATOES", "TOMATOES, CHERRY",
                          "TOMATOES, GRAPE TYPE", "TOMATOES, PLUM TYPE", "TURNIP TOPS GREENS"]
HERBS_COMMODITIES = ["ALL", "HERBS"]
ORNAMENTALS_COMMODITIES = ["ALL", "DAFFODIL", "GLADIOLA", "MISC. CHRISTMAS ITEMS", "POTTED PLANTS", "ROSE, HYBRID TEA",
                           "TULIPS"]
HEMP_COMMODITIES = ["ALL", "HEMP (SEEDS) OIL", "HEMP PROTEIN", "HEMP SEEDS-SHELLED"]

COMPOSITE_COMMODITIES = [x for x in set(FRUIT_COMMODITIES + ONIONS_AND_POTATOES_COMMODITIES + VEGETABLES_COMMODITIES +
                                        HERBS_COMMODITIES + ORNAMENTALS_COMMODITIES + HEMP_COMMODITIES)]

COMMODITY_REGIONS = ["ALL", "NATIONAL", "NORTHEAST U.S.", "SOUTHEAST U.S.", "MIDWEST U.S.", "SOUTH CENTRAL U.S.",
                     "SOUTHWEST U.S.", "NORTHWEST U.S.", "HAWAII", "ALASKA"]
COMMODITY_CATEGORIES = ["termPrice", "shipPrice", "movement", "retail"]
