COMMODITY_REGIONS = ["ALL", "NATIONAL", "NORTHEAST U.S.", "SOUTHEAST U.S.", "MIDWEST U.S.", "SOUTH CENTRAL U.S.",
                     "SOUTHWEST U.S.", "NORTHWEST U.S.", "HAWAII", "ALASKA"]
COMMODITY_CATEGORIES = ["termPrice", "shipPrice", "movement", "retail"]
COMMODITY_DATA = [
    {
        "name": "ALL",
        "commodity": "ALL",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "APPLE PEARS",
        "commodity": "APPLE PEARS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "APPLES",
        "commodity": "APPLES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "APPLES, PROCESSED",
        "commodity": "APPLES, PROCESSED",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "APRICOTS",
        "commodity": "APRICOTS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "AVOCADOS",
        "commodity": "AVOCADOS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BANANAS",
        "commodity": "BANANAS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BLACKBERRIES",
        "commodity": "BLACKBERRIES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BLUEBERRIES",
        "commodity": "BLUEBERRIES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CACTUS PEARS",
        "commodity": "CACTUS PEARS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CANTALOUPS",
        "commodity": "CANTALOUPS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CHERRIES",
        "commodity": "CHERRIES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CLEMENTINES",
        "commodity": "CLEMENTINES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CRANBERRIES",
        "commodity": "CRANBERRIES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "GRAPEFRUIT",
        "commodity": "GRAPEFRUIT",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "GRAPES",
        "commodity": "GRAPES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "HONEYDEWS",
        "commodity": "HONEYDEWS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "KIWIFRUIT",
        "commodity": "KIWIFRUIT",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "LEMONS",
        "commodity": "LEMONS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "LIMES",
        "commodity": "LIMES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "MANGOES",
        "commodity": "MANGOES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "NECTARINES",
        "commodity": "NECTARINES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ORANGES",
        "commodity": "ORANGES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PAPAYA",
        "commodity": "PAPAYA",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PEACHES",
        "commodity": "PEACHES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PEARS",
        "commodity": "PEARS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PERSIMMONS",
        "commodity": "PERSIMMONS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PINEAPPLES",
        "commodity": "PINEAPPLES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PLUMS",
        "commodity": "PLUMS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "POMEGRANATES",
        "commodity": "POMEGRANATES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PRUNES",
        "commodity": "PRUNES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "RASPBERRIES",
        "commodity": "RASPBERRIES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "SATSUMA",
        "commodity": "SATSUMA",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "STRAWBERRIES",
        "commodity": "STRAWBERRIES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TANGELOS",
        "commodity": "TANGELOS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TANGERINES",
        "commodity": "TANGERINES",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "WATERMELONS",
        "commodity": "WATERMELONS",
        "class": "FRUITS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ALL",
        "commodity": "ALL",
        "class": "ONIONS AND POTATOES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ONIONS DRY",
        "commodity": "ONIONS DRY",
        "class": "ONIONS AND POTATOES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "POTATOES",
        "commodity": "POTATOES",
        "class": "ONIONS AND POTATOES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ALL",
        "commodity": "ALL",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ARTICHOKES",
        "commodity": "ARTICHOKES",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ASPARAGUS",
        "commodity": "ASPARAGUS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BEANS",
        "commodity": "BEANS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BEETS",
        "commodity": "BEETS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BOK CHOY",
        "commodity": "BOK CHOY",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BROCCOLI",
        "commodity": "BROCCOLI",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "BRUSSELS SPROUTS",
        "commodity": "BRUSSELS SPROUTS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CABBAGE",
        "commodity": "CABBAGE",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CACTUS LEAF (NOPALES)",
        "commodity": "CACTUS LEAF (NOPALES)",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CARROTS",
        "commodity": "CARROTS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CAULIFLOWER",
        "commodity": "CAULIFLOWER",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CELERY",
        "commodity": "CELERY",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CHAYOTE",
        "commodity": "CHAYOTE",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CHINESE CABBAGE",
        "commodity": "CHINESE CABBAGE",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "COLLARD GREENS",
        "commodity": "COLLARD GREENS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CORN-SWEET",
        "commodity": "CORN-SWEET",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "CUCUMBERS",
        "commodity": "CUCUMBERS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "EGGPLANT",
        "commodity": "EGGPLANT",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "GARLIC",
        "commodity": "GARLIC",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "KALE GREENS",
        "commodity": "KALE GREENS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "LETTUCE, BOSTON",
        "commodity": "LETTUCE, BOSTON",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "LETTUCE, GREEN LEAF",
        "commodity": "LETTUCE, GREEN LEAF",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "LETTUCE, ICEBERG",
        "commodity": "LETTUCE, ICEBERG",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "LETTUCE, RED LEAF",
        "commodity": "LETTUCE, RED LEAF",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "LETTUCE, ROMAINE",
        "commodity": "LETTUCE, ROMAINE",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "MUSHROOMS",
        "commodity": "MUSHROOMS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "MUSTARD",
        "commodity": "MUSTARD",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ONIONS GREEN",
        "commodity": "ONIONS GREEN",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PEPPERS, BELL TYPE",
        "commodity": "PEPPERS, BELL TYPE",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PEPPERS, OTHER",
        "commodity": "PEPPERS, OTHER",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "PUMPKINS",
        "commodity": "PUMPKINS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "RADISHES",
        "commodity": "RADISHES",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "SALAD",
        "commodity": "SALAD",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "SPINACH",
        "commodity": "SPINACH",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "SQUASH",
        "commodity": "SQUASH",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "SWEET POTATOES",
        "commodity": "SWEET POTATOES",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "SWISS CHARD",
        "commodity": "SWISS CHARD",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TOMATILLOS",
        "commodity": "TOMATILLOS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TOMATOES",
        "commodity": "TOMATOES",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TOMATOES, CHERRY",
        "commodity": "TOMATOES, CHERRY",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TOMATOES, GRAPE TYPE",
        "commodity": "TOMATOES, GRAPE TYPE",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TOMATOES, PLUM TYPE",
        "commodity": "TOMATOES, PLUM TYPE",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TURNIP TOPS GREENS",
        "commodity": "TURNIP TOPS GREENS",
        "class": "VEGETABLES",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ALL",
        "commodity": "ALL",
        "class": "HERBS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "HERBS",
        "commodity": "HERBS",
        "class": "HERBS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ALL",
        "commodity": "ALL",
        "class": "ORNAMENTALS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "DAFFODIL",
        "commodity": "DAFFODIL",
        "class": "ORNAMENTALS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "GLADIOLA",
        "commodity": "GLADIOLA",
        "class": "ORNAMENTALS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "MISC. CHRISTMAS ITEMS",
        "commodity": "MISC. CHRISTMAS ITEMS",
        "class": "ORNAMENTALS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "POTTED PLANTS",
        "commodity": "POTTED PLANTS",
        "class": "ORNAMENTALS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ROSE, HYBRID TEA",
        "commodity": "ROSE, HYBRID TEA",
        "class": "ORNAMENTALS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "TULIPS",
        "commodity": "TULIPS",
        "class": "ORNAMENTALS",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "ALL",
        "commodity": "ALL",
        "class": "HEMP",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "HEMP (SEEDS) OIL",
        "commodity": "HEMP (SEEDS) OIL",
        "class": "HEMP",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "HEMP PROTEIN",
        "commodity": "HEMP PROTEIN",
        "class": "HEMP",
        "regions": COMMODITY_REGIONS,
    },
    {
        "name": "HEMP SEEDS-SHELLED",
        "commodity": "HEMP SEEDS-SHELLED",
        "class": "HEMP",
        "regions": COMMODITY_REGIONS,
    },
]
COMMODITY_CLASSES = ["ALL"]
COMMODITY_CLASSES.extend([x for x in set([x["class"] for x in COMMODITY_DATA])])
FRUIT_COMMODITIES = [x for x in set([x["name"] for x in COMMODITY_DATA if x["class"] == "FRUITS"])]
ONIONS_AND_POTATOES_COMMODITIES = [x for x in
                                   set([x["name"] for x in COMMODITY_DATA if x["class"] == "ONIONS AND POTATOES"])]
VEGETABLES_COMMODITIES = [x for x in set([x["name"] for x in COMMODITY_DATA if x["class"] == "VEGETABLES"])]
HERBS_COMMODITIES = [x for x in set([x["name"] for x in COMMODITY_DATA if x["class"] == "HERBS"])]
ORNAMENTALS_COMMODITIES = [x for x in set([x["name"] for x in COMMODITY_DATA if x["class"] == "ORNAMENTALS"])]
HEMP_COMMODITIES = [x for x in set([x["name"] for x in COMMODITY_DATA if x["class"] == "HEMP"])]
COMPOSITE_COMMODITIES = [x for x in set(FRUIT_COMMODITIES + ONIONS_AND_POTATOES_COMMODITIES + VEGETABLES_COMMODITIES +
                                        HERBS_COMMODITIES + ORNAMENTALS_COMMODITIES + HEMP_COMMODITIES)]
